### ISSUE TITLE
Upgrade to grocy 3.1.0

### ISSUE THREAD

**Issue by jayaddison** [grocy/grocy-docker#135]
Grocy 3.1.0 [has been released](https://github.com/grocy/grocy/releases/tag/v3.1.0) and is best supported under PHP version 8.

It looks like we're nearly ready to migrate the `grocy-docker` container images to PHP 8.  [JSON support is always available](https://www.php.net/ChangeLog-8.php) from that version onwards so we should be able to [remove this dependency installation line](https://github.com/grocy/grocy-docker/blob/9361f4c00632ddf7895b2f024473993ddb0526e6/Dockerfile-grocy-backend#L32).

However Alpine's [currently-packaged version of `composer` depends on PHP 7](https://gitlab.alpinelinux.org/alpine/aports/-/blob/a470a056487ef30f5bf3019d04db1c3de17d8c79/community/composer/APKBUILD#L10).  Grocy (and our images) depend on `composer` for dependency installation, so we may need to wait for an updated `composer` Alpine package with PHP 8 support to land.

**Comment by HamburgerJungeJr** [comment]
I dont think that composer will change its requirements to php8 in the near future as composer depends on the symlink /usr/bin/php. This will only be created by php7 because it is currently the default php version as only a few applications support php8 as stated here: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12308

Therefore I modified  the dockerfile to use a manually installed composer with php8: https://github.com/grocy/grocy-docker/pull/137

**Comment by jayaddison** [comment]
Resolved by #137.
