### ISSUE TITLE
Update grocy?

### ISSUE THREAD

**Issue by MatFluor** [grocy/grocy-docker#20]
Hi,

maybe a silly question. I want to upgrade to grocy 2.4.4, but whatever I do, it stays on v 2.2.0. Are there steps I forgot (given I'm new to docker)?

1. git pull this repo
2. docker-compose pull
3. docker-compose build --no-cache --pull (I see that grocy-2.4.4 is being unzipped)
4. docker-container up
-> still grocy v2.2.0

Thank you for any suggestions

**Comment by Comrade3** [comment]
I think this is a problem with the persistent volume I made. This happened to me when I was testing something. I just deleted the volume and let it remake a new one, but that will lose all the data you have. you could test if this would fix it without deleting your old database volume by changing lines 28 and 37 in the docker-compose.yml from database to database2 or something.Then delete you containers(docker rm grocy grocy-nginx) and run the docker-compose up. 

To switch back to your old database you just change the docker-compose.yml back and delete your containers(docker rm grocy grocy-nginx) and run the docker-compose up again.

By the way if your using the docker-compose pull you don't need to docker-compose build or vice versa. Pull gets the images from the repository and build uses the dockerfile you have to build the image.

Also since your new to docker you might want to check out [Portainer](https://hub.docker.com/r/portainer/portainer) it helped me a lot when I first started using docker. I mostly use the command lines now, but the Portainer GUI makes troubleshooting easier.

**Comment by MatFluor** [comment]
Thanks for your suggestion!

When I switch to another database, it works - but changing back to the old database unfortunately doesn't. OF course removing the volume works as well, but as you said, data loss. I went that way, since I didn't do too much work in there, but for future updates it might be worth looking into I think.

**Comment by schildgenb** [comment]
Having the same issues here that it stays on 2.2. I do not really want to lose data if I don't have too. Any ideas @talmai?

**Comment by andreas5232** [comment]
I just stumbled upon the same problem. Even though `docker-compose pull` recreated the containers, they were still running an old version of grocy. Since I'm not very familiar with the grocy internals (yet), I don't know what the officially intended way of upgrading grocy-docker is.

What I did to upgrade my grocy-docker instance is:
- Use the shell of your hosts OS, not within the docker container
- Find the path to your grocy data: 
`docker inspect --format='{{json .Mounts}}' grocy | python -m json.tool`
- Make sure to backup all your grocy files
- Change into the _data dir: `cd /var/lib/docker/volumes/grocydocker_database/_data`
- Run the provided update script: `bash ./update.sh`
- Enjoy your updated grocy! :tada: 

Please let me know, if this works for you. Maybe we can add this little upgrade help to the README then.

**Comment by jayaddison** [comment]
Resolving this issue as stale; please reopen and provide steps to reproduce the problem if you're still experiencing this issue and would like help investigating it.
