### ISSUE TITLE
Plan from migrating away from dockerhub?

### ISSUE THREAD

**Issue by hydrargyrum** [grocy/grocy-docker#209]
Grocy's docker image is currently hosted on dockerhub, which has released a [new policy that might endanger your hosting there](https://blog.alexellis.io/docker-is-deleting-open-source-images/) ([see also](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/)). Do you have any plans for migrating hosting elsewhere?

**Comment by danieljkemp** [comment]
It looks like they canceled that policy change. (https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/)

Either way the dockerhub rate limits can cause issues on more complex setups.

GHCR could be a worthwhile consideration: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by jayaddison** [comment]
Short answer: not sure yet.

Longer answer: it's an economic problem related to the cost of hosting and delivering the container images, and the benefit of using the containerized application (noting as usual that it's entirely possible to run `grocy` without containers at all)

Some factors:

- What are the time-saving and cost-saving benefits to homes for using Grocy?
- What are the compute resource costs to homes for using Grocy?
- What are the compute resource costs to homes to build a Grocy container from scratch?  (and related: are the container builds [reproducible](http://www.reproducible-builds.org), so that each home knows they have the correct software?  if not, where is the problem and what can we do about that?)
- What are the hosting and delivery costs to Docker Hub for the container images, and what could we do to reduce those?
- What are the hosting and delivery costs to GitHub for the source code and build processes, and what could we do to reduce those?
- Are other container image hosting providers likely to have better economics in terms of image hosting?  Why?  Or why not?

Compared to larger and more popular container images, I hope that the `grocy` containers are doing a reasonable job; my goal is to keep them small, compatible and buildable from source, and to keep the build process lightweight and repeatable (but I admit that the output images are not (easily?) reproducible yet).

(I'd probably welcome pull requests to add GitHub's container registry as a push destination -- hopefully that'd be quite straightforward, maybe as short as two lines of workflow code)

**Comment by xxxcrow** [comment]
Reliance of github which is owned by Microsoft can become tricky too
There are many registries out there, maybe some are worth trying, or self hosting, I'm pretty sure self hosting would cost less than $420 a year
Plus, as you say "grocy is a pretty php script" (or sth like that), so maybe just use dockerfiles 
I know using dockerfiles will mean "we are poor", but docker becomes anti open source, so we should move
