### ISSUE TITLE
Docker image not found (with bages linked)

### ISSUE THREAD

**Issue by rugk** [grocy/grocy-docker#232]
https://hub.docker.com/r/grocy/grocy/ is a 404 link. Also the badge in the Readme shows an error (due to this).

The later link https://hub.docker.com/u/grocy is found though, but hmm?

**Comment by jayaddison** [comment]
Thanks @rugk, well spotted.

As some context: Grocy for Docker is distributed as a pair of containers, one for each of the two server processes (a PHP webserver for the dynamic, backend code -- and an `nginx` server to serve the static frontend HTML, CSS and JS content to web browsers).

Historically one of the two containers _was_ named `grocy/grocy` -- this was the backend.  To attempt to make their purposes clearer, I renamed `grocy/grocy` to `grocy/backend` in #133 (and `grocy/nginx` to `grocy/frontend`).

Note: it would be possible to place multiple services into a single container, and in that case the name `grocy/grocy` would seem fine to me.  However, it is a [recommended best practice to separate services into individual containers](https://docs.docker.com/config/containers/multi-service_container/).

...in any case, though - you're correct, I forgot to update that README link - so I'll get that fixed in a moment.
