### ISSUE TITLE
Adding LANGUAGE option to docker-compose.yml file

### ISSUE THREAD

**Issue by SirTerrific** [grocy/grocy-docker#5]
HI there,

Thanks for the project, it's really nice. 
I have a question when will we be able to use the French language ?

Thanks.

**Comment by Comrade3** [comment]
I have made a pull request that updates to version 1.23.1 which adds French. To enable it though you have to change `('CULTURE', 'en')` to `('CULTURE', 'fr')` in the `data/config.php` file that is in the `grocy/grocy-docker:grocy` container. There is probably a easy way to do this using the docker-compose file, but I don't know how to do it. Hopefully @talmai  knows how to do something like that.

I did find a way to switch the language though.
1.`sudo docker exec -i -t grocy /bin/sh`
2.`apk add nano`
3.`nano ../data/config.php`
4.change `('CULTURE', 'en')` to `('CULTURE', 'fr')`
5.use ctrl+x to exit. Y then enter to save.
6.`exit`

To use this you will have to wait till my pull request is accepted though. Or you can use [https://github.com/Comrade3/grocy-docker](https://github.com/Comrade3/grocy-docker) if you want. But if you do **don't** pull the image before with `docker pull grocy/grocy-docker:grocy` or `docker-compose pull`. Just run `docker-compose up` so it builds from the Dockerfile-grocy.

**Comment by talmai** [comment]
I'm out on holidays (which is why I took so long to reply to this). What if we try the following:

in `docker-compose.yml` add a environment section:

    environment:
      - CULTURE=en

(this then can be changed by the user before they run `docker-compose up`).

We then would need to add an ENTRYPOINT to `Dockerfile-grocy` so that a script is executed every time. The idea behind this script would be to update the data/config.php file.

Another (simpler) solution is removing CULTURE from the /data/config.php file altogether (this could be done via `sed` in the `Dockerfile-grocy` file, and testing if grocy already uses the environmental variable.

**Comment by berrnd** [comment]
grocy/grocy#118 is done, so environment variables for all `config.php` settings will work in the next release (will push one today to include this) - but they need to be prefixed with `GROCY_`, so e. g. `GROCY_CULTURE`...

**Comment by Comrade3** [comment]
I created a pull request for the language option using the `GROCY_CULTURE` in the docker-compose.yml. :) @talmai you will probably want to add instructions in the README.

**Comment by SirTerrific** [comment]
Nice thanks for your work ! I can't wait to use it at home !

**Comment by talmai** [comment]
merged into master
